import Head from 'next/head'
import { useEffect, useRef } from "react"

import { Initialise  } from "../webgl/procedural-terrain"
import meshLoading from '../webgl/mesh-loading'
import styles from '../styles/Home.module.css'

export default function Home() {
  const ref = useRef();

  useEffect(()=>{
    const gl = ref.current.getContext('webgl2');
    
    const loop = Initialise(gl, ref.current);
    // const loop = meshLoading(gl, ref.current);
    requestAnimationFrame(loop);
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Procedural Terrain Generation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <canvas width="720" height="480" ref={ref}></canvas>
      </main>

    </div>
  )
}
